### ISSUE TITLE
Driver update for dremio 18.1.0 and metabase 0.41.0

### ISSUE THREAD

**Issue by urba1n** [Baoqi/metabase-dremio-driver#3] opened 2021-10-08 13:01 UTC
Do you plan to update the driver to support latest version of dremio and metabase ?

**Comment by Baoqi** [comment] 2021-10-09 03:51
> Do you plan to update the driver to support latest version of dremio and metabase ?

Hi, @urba1n 

There seems no incompatible changes for metabase-dremio-driver to work with newer version of dremio or metabse. So, current version should works in metabase 0.41.0 and dremio 18.1.0. (I tested on metabase 0.41.0)

Did you encounter some issues when run current version of metabase-dremio-driver?

**Comment by Baoqi** [comment] 2021-10-13 03:42
Hi, @urba1n 

    I can reproduce this issue. The root cause of this is: dremio can not parse the following SQL

```
SET SESSION TIMEZONE TO 'Europe/Zurich';
```

Actually, dremio don't have anything similar with this statement.  Currently, Dremio assume all datetime in UTC (GMT) timezone, and only support one function CONVERT_TIMEZONE to let user explicitly choose columns and explicitly select source/target timezone to convert.  But this is far away from what "SET SESSIOn TIMEZONE" work.

So, currently, for Dremio in Metabase. the "Settings" -> "Localization" -> "Report Timezone" , we can only use "Database Default" now. 







> Hi @Baoqi,
> 
> I get some warnings and an error related to usage of timezone (see below). For the rest, everything seems to work correctly.
>

**Comment by cbfranca** [comment] 2022-03-24 11:29
Hello,

Is it working with current versions of dremio and metabase?

Tks

**Comment by slamer59** [comment] 2022-04-03 11:37
@Baoqi it seems to work with the last dremio / metabase. However do you think we can implement an update to follow the drivers update ? 

I can help on CI part but I am not really familiar with Clojure build.

**Comment by Baoqi** [comment] 2022-05-16 07:43
> @Baoqi it seems to work with the last dremio / metabase. However do you think we can implement an update to follow the drivers update ?
> 
> I can help on CI part but I am not really familiar with Clojure build.

Hi, @slamer59,  I just got time to work on this recently. I just added the CI in main branch, using github's actions.  (Note: I mainly copied the logic from https://github.com/firebolt-db/metabase-firebolt-driver project, which is Apache V2 licensed),  seems works fine.  So, I just close this issue currently. Thanks.

**Closed by Baoqi** 2022-05-16 07:43 UTC
